# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: âœ… CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * 0"

jobs:
  libhal:
    uses: ./.github/workflows/library.yml
    with:
      library: libhal
      repo: libhal/libhal
    secrets: inherit

  libhal-armcortex:
    uses: ./.github/workflows/library.yml
    with:
      library: libhal-armcortex
      repo: libhal/libhal-armcortex
    secrets: inherit

  libhal-util:
    uses: ./.github/workflows/library.yml
    with:
      library: libhal-util
      repo: libhal/libhal-util
    secrets: inherit

  libhal-lpc40:
    uses: ./.github/workflows/library.yml
    with:
      library: libhal-lpc40
      repo: libhal/libhal-lpc40
    secrets: inherit

  libhal-soft:
    uses: ./.github/workflows/library.yml
    with:
      library: libhal-soft
      repo: libhal/libhal-soft
    secrets: inherit

  libhal-lpc4072:
    uses: ./.github/workflows/platform_deploy.yml
    with:
      library: libhal-lpc40
      repo: libhal/libhal-lpc40
      profile: lpc4072
      processor_profile: https://github.com/libhal/libhal-armcortex.git
    secrets: inherit

  libhal-lpc4088:
    uses: ./.github/workflows/platform_deploy.yml
    with:
      library: libhal-lpc40
      repo: libhal/libhal-lpc40
      profile: lpc4088
      processor_profile: https://github.com/libhal/libhal-armcortex.git
    secrets: inherit

  libhal-cortex-m0:
    uses: ./.github/workflows/platform_deploy.yml
    with:
      library: libhal-armcortex
      repo: libhal/libhal-armcortex
      profile: cortex-m0
    secrets: inherit

  libhal-soft-package:
    uses: ./.github/workflows/deploy.yml
    with:
      library: libhal-soft
      repo: libhal/libhal-soft
    secrets: inherit

  libhal-rmd-demos-lpc4078:
    uses: ./.github/workflows/demo_builder.yml
    with:
      library: libhal-rmd
      repo: libhal/libhal-rmd
      profile: lpc4078
      processor_profile: https://github.com/libhal/libhal-armcortex.git
      platform_profile: https://github.com/libhal/libhal-lpc40.git
    secrets: inherit

  libhal-rmd-demos-lpc4074:
    uses: ./.github/workflows/demo_builder.yml
    with:
      library: libhal-rmd
      repo: libhal/libhal-rmd
      profile: lpc4074
      processor_profile: https://github.com/libhal/libhal-armcortex.git
      platform_profile: https://github.com/libhal/libhal-lpc40.git
    secrets: inherit
